# Use container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

scala:
   - 2.10.7
   - 2.11.12
   - 2.12.4

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test $(if [[ "${TRAVIS_SCALA_VERSION}" == "2.12.4" ]]; then echo testConscript ; fi)
  - if [[ "${TRAVIS_SCALA_VERSION}" == "2.11.12" ]]; then ./publish.sh; fi

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global:
    secure: Pdcegq79mokfGhVVEAvOINWXnE1NgBYXb+jDlWZQxCPMJN1LmCRuQsAlDEE76X5gTsZx/3IBEweCGR1scFQOl2c9WnrOrFtH54PFSw6kf0IN8u85RyrK6PaxYc4CYJisVmAMU0HP6a4/UBj+RD+4IAxpKBeqSEcxJpU6deW6P9s=
