# Use container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

# Cross built for 2.10 and 2.11
scala:
   - 2.10.6
   - 2.11.8

jdk:
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
